server {
    listen 80;
    server_name gdg.admin.dhanrajj.me;

    # 🔐 ACME challenge (MUST be first)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        proxy_pass http://client_admin:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
