server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name gdg.server.dhanrajj.me;

    ssl_certificate     /etc/letsencrypt/live/gdg.admin.dhanrajj.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gdg.admin.dhanrajj.me/privkey.pem;


    location / {
        proxy_pass http://server:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
