services:
  server:
    build:
      context: ./Server
      dockerfile: ../Docker/dockerfile.server
    env_file:
      - ./Server/.env
    
  client_admin:
    build:
      context: ./Client_admin
      dockerfile: ../Docker/dockerfile.client_admin
    env_file:
      - ./Client_admin/.env
    depends_on:
      - server
    
  client_main:
    build:
      context: ./Client_main
      dockerfile: ../Docker/dockerfile.client_main
    env_file:
      - ./Client_main/.env
    depends_on:
      - server

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Nginx/sites:/etc/nginx/conf.d:ro
    depends_on:
      - client_admin
      - server
      