#stage 1: build frontend
FROM node:22-alpine  AS builder

# Set working directory

WORKDIR /app/client_admin

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install

COPY . .


RUN npm run build

#stage 2: serve frontend with nginx server

FROM nginx:alpine

COPY --from=builder /app/frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

