FROM node:22-alpine AS builder

WORKDIR /app

ARG VITE_API_BASE_URL
ARG VITE_PUBLIC_S3_URL

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_PUBLIC_S3_URL=$VITE_PUBLIC_S3_URL

COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html
