#stage 1: build frontend
FROM node:22-alpine  AS builder

# Set working directory

WORKDIR /app

COPY package*.json ./


RUN npm install

COPY . .


RUN npm run build

#stage 2: serve frontend with nginx server

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]