name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./Server
          file: ./Docker/dockerfile.server
          push: true
          tags: |
            dhanraj11/gdg-website-server:latest
            dhanraj11/gdg-website-server:${{ github.sha }}

      - name: Build and Push Client_admin Image
        uses: docker/build-push-action@v4
        with:
          context: ./Client_admin
          file: ./Docker/dockerfile.client_admin.prod
          push: true
          tags: |
            dhanraj11/gdg-website-client-admin:latest
            dhanraj11/gdg-website-client-admin:${{ github.sha }}
          build-args: |
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
            VITE_PUBLIC_S3_URL=${{ secrets.VITE_PUBLIC_S3_URL }}

      - name: Build and push Client_main Image
        uses: docker/build-push-action@v4
        with:
          context: ./Client_main
          file: ./Docker/dockerfile.client_main.prod
          push: true
          tags: |
            dhanraj11/gdg-website-client-main:latest
            dhanraj11/gdg-website-client-main:${{github.sha}}
          build-args: |
              VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
              VITE_PUBLIC_S3_URL=${{ secrets.VITE_PUBLIC_S3_URL }}


